export const products = [
    {
        id : 1,
        name : "OpenDream",
        category : "Image generation AI Services",
        fund : "$2000",
        percent : "60%",
        image : "/Images/Project/opendream.jpg",
        website : "https://opendream.ai/",
        overview : "OpenDream is an AI-powered art generation tool that allows users to use the power of AI to generate their own art in seconds with simple prompts. This tool is available online and has plenty of customization options to make your images stand out. Additionally, our servers use A100 graphics processing units (GPUs), resulting in incredibly fast average generation times. OpenDream can queue up to 20 images and generate up to 3 images at the same time, making it faster than using a 6x RTX 3090. You can also build, improve, tweak, modify, and enhance the images you create using one of four AI models. Additionally, users can customize advanced settings to fine-tune their images. OpenDream is a useful tool that helps students, professionals, artists, or anyone else, even without a graphic design background, produce professional results. A free plan is also available, but it has limitations on image queuing, simultaneous generation, and settings. If you want more credits or features, you can sign up for a paid plan. Overall, OpenDream is an efficient and easy-to-use AI tool to generate your own art in seconds.",
    },
    {
        id : 2,
        name : "Soundraw",
        category : "Music AI Service",
        fund : "$500",
        percent : "45%",
        image : "/Images/Project/soundraw.jpg",
        website : "https://soundraw.io/",
        overview : "Soundraw’s biggest selling point is its AI music composition tool. This feature is what sets it apart from other music production software. The AI technology allows you to create music compositions without any prior knowledge of music theory or composition. All you have to do is select the genre, instruments, and tempo, and Soundraw will generate a unique composition for you. The AI technology analyzes your selection and creates a melody that fits the chosen genre and instruments. You can further customize your composition by selecting the chord progression, melody, and other parameters. The final result is a professional-sounding track that would take hours to create manually.",
    },
    {
        id : 3,
        name : "Simplified",
        category : "Text generation",
        fund : "$1000",
        percent : "80%",
        image : "/Images/Project/simplified.jpg",
        website : "https://simplified.com/ai-writer/",
        overview : "Simplified is the one app to create, collaborate, and scale your marketing. Design, write marketing copy, create videos, collaborate, and publish to socials—all in the same place. Built for speed and simplicity, Simplified helps over 2000,000 creators, marketers and businesses to scale their marketing, streamline their workflows, and get work done in a few clicks. With a no-code design editor, AI writer, stunning templates, multiple brand kits, unlimited workspaces, and in-app publishing, you can start and finish your marketing without switching tabs. Ever.",
    },
    {
        id : 4,
        name : "Gencraft",
        category : "Video AI generation",
        fund : "$1500",
        percent : "50%",
        image : "/Images/Project/gencraft.jpg",
        website : "https://gencraft.com/",
        overview : "Gencraft is an AI art generator tool that allows users to create stunning and personalized art photos from a few words, using their imagination as a canvas. The tool provides diverse visual categories, such as art, fashion, and video games, to assist in producing perfect personalized results. Gencraft offers an inspiration feature that helps users overcome writer’s block by allowing them to visualize new ideas by adding keywords that inspire them, then watch their words come to life.Gencraft is available across all devices, including web, iOS, and Android platforms, which makes it easily accessible for users to showcase their creative brand, find their voice and create content that truly represents them. The tool offers many styles that can be paired with text prompts to help elevate creativity for more personalized results.The platform is user-friendly, with a free version that allows people to explore the tool and the final art generated.",
    },
    {
        id : 5,
        name : "Soundful",
        category : "Music AI Service",
        fund : "$1000",
        percent : "35%",
        image : "/Images/Project/soundful.jpg",
        website : "https://soundful.com/",
        overview : "Soundful is a website in the AI music space that's garnered some attention for its high quality and customizable compositions. The software uses complex algorithms to create one-of-a-kind AI-generated music that can be modified to suit specific needs. While there are plenty of websites to download free and copyright-free music, Soundful is unique because it lets you, the user, experiment with and manipulate the outcome of the composition. And the best part is that it's royalty-free—created entirely by an algorithm.",
    },
    {
        id : 6,
        name : "Nightcafé",
        category : "Image generation AI Services",
        fund : "$2000",
        percent : "65%",
        image : "/Images/Project/nightcafé.jpg",
        website : "https://creator.nightcafe.studio/",
        overview : "NightCafe Studio aims to democratize the process of making AI art. Contrary to popular belief, AI is not intended to replace artists in the arts field. It exists to open up the creation of art to the general public. We now live in a world where you can tell a machine to make whatever art you desire. Everyone interested, not just those with coding experience, deserves to experience this. In the world of AI art generators, NightCafe AI is a well-known brand. With the help of its many preset effects, which vary from cosmic to oil painting and more, it may produce a variety of artistic media. NightCafe AI enables you to make an image in just a few minutes. You can purchase the AI-generated artwork from their website, and the application is free to use (with some limitations). If you choose to purchase it, the item can be printed and mailed to you as a picture.",
    },

]